services:
  web:
    build:
      context: .
      args:
        - NEXT_PUBLIC_CONTENTFUL_ACCESS_TOKEN=${NEXT_PUBLIC_CONTENTFUL_ACCESS_TOKEN}
        - NEXT_PUBLIC_CONTENTFUL_SPACE_ID=${NEXT_PUBLIC_CONTENTFUL_SPACE_ID}
        - NEXT_PUBLIC_CONTENTFUL_API_URL=${NEXT_PUBLIC_CONTENTFUL_API_URL}
        - NEXT_PUBLIC_YOUTUBE_API_KEY=${NEXT_PUBLIC_YOUTUBE_API_KEY}
        - NEXT_PUBLIC_YOUTUBE_API_URL=${NEXT_PUBLIC_YOUTUBE_API_URL}
        - NEXT_PUBLIC_YOUTUBE_CHANNEL_ID=${NEXT_PUBLIC_YOUTUBE_CHANNEL_ID}
        - NEXT_PUBLIC_CART_STORAGE_KEY=${NEXT_PUBLIC_CART_STORAGE_KEY}
        - NEXT_PUBLIC_COLOMBIA_API_URL=${NEXT_PUBLIC_COLOMBIA_API_URL}
        - NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL}
    ports:
      - "3000:3000"